const isGitHubPages = location.hostname.endsWith('github.io');
const isRawGitHack = location.hostname === 'raw.githack.com';
const rawBase = isRawGitHack
  ? location.pathname.match(/^\/[^/]+\/[^/]+\/[^/]+\/web/)?.[0] || ''
  : '';
const hostedPath = isGitHubPages
  ? location.pathname.replace(/^\/GloboVerse/, '')
  : isRawGitHack
    ? location.pathname.replace(rawBase, '')
    : location.pathname;
const path = hostedPath.replace(/\/$/, '') || '/';

const nav = `
<nav class="nav">
  <a class="brand" href="/"><span class="brand-dot"></span>TAJ AL</a>
  <button class="menu" aria-label="Open menu">☰</button>
  <div class="links">
    ${[['/','Home'],['/services','Services'],['/products','Products'],['/projects','Projects'],['/about','About'],['/contact','Contact']].map(([u,n])=>`<a href="${u}" class="${path===u?'active':''}">${n}</a>`).join('')}
    <a class="cta" href="/contact">Start a Project <span>↗</span></a>
  </div>
</nav>`;

const footer = `<footer>
  <div class="footer-top">
    <div class="footer-brand"><a class="brand" href="/"><span class="brand-dot"></span>TAJ AL</a><p>AI & Digital Studio<br>Building digital products from Tajikistan to the world.</p></div>
    <div class="footer-col"><b>Explore</b><a href="/services">Services</a><a href="/products">Products</a><a href="/projects">Projects</a><a href="/about">About</a></div>
    <div class="footer-col"><b>Company</b><a href="/contact">Contact</a><a href="/process">Process</a><a href="/faq">FAQ</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div>
    <div class="footer-col"><b>Connect</b><a href="mailto:tajalsupport@gmail.com">Email</a><a href="#">Instagram ↗</a></div>
  </div>
  <div class="footer-bottom"><span>© 2026 Taj Al. All rights reserved.</span><span>A Taj Al Product.</span></div>
</footer>`;
const hero = (eyebrow,title,lead)=>`<header class="page-hero reveal"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="lead">${lead}</p></header>`;
const list = (num,title,tag,desc,features='')=>`<article class="list-card"><span class="tag">${num}</span><div><div class="tag">${tag}</div><h2>${title}</h2><p>${desc}</p>${features?`<div class="features">${features.split(',').map(x=>`<span>${x}</span>`).join('')}</div>`:''}</div><a class="circle-link" href="/contact" aria-label="View ${title}">↗</a></article>`;

const pages = {
'/': `<main>
<header class="hero reveal"><div class="hero-grid"></div><div class="orb"></div><div class="eyebrow">Independent AI & Digital Studio</div><h1>We build digital products for the <span>future.</span></h1><p class="lead">AI-powered apps, modern websites and distinctive digital brands — built from idea to launch.</p><div class="actions"><a class="cta" href="/contact">Start a Project</a><a class="cta ghost" href="/projects">Explore Our Work</a></div></header>
<div class="ticker"><span>AI</span><i></i><span>APPS</span><i></i><span>WEBSITES</span><i></i><span>BRANDING</span></div>
<section><div class="section-head"><div><div class="kicker">01 — Capabilities</div><h2>Digital ideas.<br>Real products.</h2></div><p>We turn ideas into useful digital experiences — from websites and mobile apps to AI-powered products and modern brand identities.</p></div><div class="cards">
${[['01','⌘','AI Solutions','Smart tools and AI-powered experiences for modern businesses.'],['02','◫','Apps','Mobile applications designed to be fast, intuitive and scalable.'],['03','◎','Websites','Modern websites built to represent your business and convert visitors.'],['04','✦','Branding','Visual identities that make your brand recognizable and memorable.']].map(x=>`<article class="card"><span class="card-num">${x[0]}</span><div class="icon">${x[1]}</div><h3>${x[2]}</h3><p>${x[3]}</p></article>`).join('')}</div></section>
<section class="statement"><div><div class="label">BUILT FROM TAJIKISTAN 🇹🇯</div><h2>Designed for<br>the World. 🌍</h2><p>Local roots. Global standards. We create thoughtful digital experiences for ambitious people everywhere.</p></div><div class="arrow">↗</div></section>
</main>`,
'/services': `<main>${hero('Services — 01','What We Do','From a simple idea to a complete digital product. We combine strategy, design and technology to build work that lasts.')}<div class="content">${list('01','Website Development','Design + Development','Modern, responsive websites designed for businesses, startups and personal brands.','UI/UX,Responsive design,Development,Optimization,Deployment')}${list('02','App Development','Mobile Products','We turn ideas into mobile applications designed around real users and built to scale.','Product strategy,UX design,Development,Launch')}${list('03','AI Solutions','Intelligent Systems','We integrate AI into products and workflows to make businesses smarter and more efficient.','AI integration,Automation,Custom tools')}${list('04','Branding','Identity Design','Logos, visual identity and digital branding designed to make your business stand out.','Strategy,Visual identity,Digital guidelines')}</div></main>`,
'/products': `<main>${hero('Products — 02','Products by Taj Al',"We don't just build for clients. We build our own products too — useful experiments made for a connected world.")}<div class="content">${list('01','Globoverse','3D Digital World / Map Experience','Explore, discover and connect through a new generation of digital experiences.')}${list('02','Taj Al','AI-powered Digital Product','One of our first products under the growing Taj Al ecosystem.')}${list('03','Coming Next','In Development','A new idea is taking shape. More details will be shared soon.')}</div></main>`,
'/projects': `<main>${hero('Selected Work — 03','Ideas, made real.','A collection of digital products, websites, apps and brand identities created by Taj Al.')}<div class="content">${list('01','Taj Al','AI / Branding','A bold identity and digital home for an independent studio with global ambition.')}${list('02','Globoverse','App / 3D Map','A multilingual social world designed to help people connect across cultures.')}${list('03','Project 03','Website','A modern web experience currently being crafted behind the scenes.')}</div></main>`,
'/about': `<main>${hero('About — 04','About Taj Al','Taj Al is an independent AI & Digital Studio focused on building modern digital products, experiences and brands.')}<div class="content"><div class="two-col"><div class="copy-block"><div class="kicker">Our Vision</div><h2>Simple ideas can change everything.</h2><p>We believe great products start with a simple idea — and the right technology can turn that idea into something people use every day.</p></div><div class="copy-block"><div class="kicker">Our Mission</div><h2>Useful, beautiful, innovative.</h2><p>Our mission is to build digital products that connect ideas with people, combining clarity, creativity and modern technology.</p></div></div><div class="origin"><div class="kicker">Our origin</div><h2>From Tajikistan <span>🇹🇯</span><br>to the World <span>🌍</span></h2><p class="lead">Taj Al started from Tajikistan with a global ambition — to create digital products for people and businesses around the world.</p></div></div></main>`,
'/contact': `<main>${hero('Contact — 05',"Let's Build Something.","Have an idea for an app, website, AI product or brand? Tell us about it. We'll discuss how Taj Al can help.")}<div class="content contact-grid"><aside><div class="kicker">Start a conversation</div><p class="contact-note">Good products begin with honest conversations. Share the idea — even if it is only a sketch.</p><p>Email<br><a class="contact-email" href="mailto:tajalsupport@gmail.com">tajalsupport@gmail.com</a></p></aside><form id="contact-form"><div class="field"><label for="name">Name</label><input id="name" required placeholder="Your name"></div><div class="field"><label for="email">Email</label><input id="email" type="email" required placeholder="you@company.com"></div><div class="field"><label for="company">Company / Project</label><input id="company" placeholder="Project name"></div><div class="field"><label for="brief">What do you want to build?</label><textarea id="brief" required placeholder="Tell us about the idea, the audience and your goals..."></textarea></div><div class="field"><label for="budget">Budget (optional)</label><select id="budget"><option value="">Select a range</option><option>$1k — $5k</option><option>$5k — $15k</option><option>$15k+</option></select></div><button class="cta" type="submit">Send Project Request →</button><p id="form-status" aria-live="polite"></p></form></div></main>`,
'/process': `<main>${hero('Our Process','From Idea to Product','A clear, collaborative process that keeps momentum high and surprises low.')}<div class="content">${[['01','Discover','We understand your idea, goals and audience.'],['02','Design','We create the visual direction and user experience.'],['03','Build','We develop the website, app or digital product.'],['04','Test','We test the product, fix issues and improve the experience.'],['05','Launch','We prepare your product for real users.'],['06','Grow','We continue improving based on real-world feedback.']].map(x=>`<div class="process-step"><b>${x[0]}</b><h2>${x[1]}</h2><p>${x[2]}</p></div>`).join('')}</div></main>`,
'/faq': `<main>${hero('FAQ','Answers, clearly.','A few common questions about working with Taj Al.')}<div class="content">${[['What does Taj Al build?','We build websites, mobile apps, AI-powered solutions and digital brands.'],['Do you work with international clients?','Yes. Taj Al is building products and services for clients and users worldwide.'],['How do I start a project?',"Send us your idea through the contact form or email. We'll review it and discuss the next steps."],['Can you build an app from just an idea?','Yes. We can help transform an idea into a structured digital product, from concept and design to development.']].map(x=>`<div class="faq-item"><button>${x[0]} <span>＋</span></button><div class="faq-answer">${x[1]}</div></div>`).join('')}</div></main>`,
'/privacy': `<main>${hero('Legal','Privacy Policy','Last updated: September 9, 2026')}<div class="content legal"><p>Taj Al respects your privacy. This policy explains what information may be collected when you use this website and how it is handled.</p><h2>Information we collect</h2><p>When you contact us, we may collect your name, email address, company or project details, budget range and any information included in your message.</p><h2>How we use information</h2><p>We use this information only to respond to enquiries, provide requested services, improve this website and meet legal obligations. We do not sell personal information.</p><h2>Contact</h2><p>Questions can be sent to <a class="contact-email" href="mailto:tajalsupport@gmail.com">tajalsupport@gmail.com</a>.</p></div></main>`,
'/terms': `<main>${hero('Legal','Terms of Service','Last updated: September 9, 2026')}<div class="content legal"><p>By using this website, you agree to these terms. The website provides general information about Taj Al and its services.</p><h2>Project engagements</h2><p>Specific scope, timing, payment, ownership and support terms will be set out in a separate written proposal or client agreement before paid work begins.</p><h2>Intellectual property</h2><p>Unless otherwise stated, the Taj Al name, identity, website copy and visual materials are owned by Taj Al and may not be reproduced without permission.</p><h2>Contact</h2><p>Questions can be sent to <a class="contact-email" href="mailto:tajalsupport@gmail.com">tajalsupport@gmail.com</a>.</p></div></main>`
};

document.getElementById('app').innerHTML = `<div class="noise"></div>${nav}${pages[path] || pages['/']}${footer}`;
// GitHub project pages are hosted below /GloboVerse; keep local preview URLs clean.
if (isGitHubPages || isRawGitHack) {
  const base = isGitHubPages ? '/GloboVerse' : rawBase;
  document.querySelectorAll('a[href^="/"]').forEach(link => {
    link.href = `${base}${link.getAttribute('href')}`;
  });
}
document.querySelector('.menu')?.addEventListener('click',()=>document.querySelector('.links').classList.toggle('open'));
document.querySelectorAll('.faq-item button').forEach(b=>b.addEventListener('click',()=>b.parentElement.classList.toggle('open')));
document.getElementById('contact-form')?.addEventListener('submit',e=>{e.preventDefault(); const s=document.getElementById('form-status'); s.textContent='Thank you — your email app is opening.'; const subject=encodeURIComponent(`Project enquiry — ${document.getElementById('company').value||'New project'}`); const body=encodeURIComponent(`Name: ${document.getElementById('name').value}\nEmail: ${document.getElementById('email').value}\nBudget: ${document.getElementById('budget').value}\n\n${document.getElementById('brief').value}`); location.href=`mailto:tajalsupport@gmail.com?subject=${subject}&body=${body}`;});
